<template>
    <div>
        <h1>Upload photos</h1>
        <label class="form-label" for="customFile">Default file input example</label>
        <input type="file" class="form-control" id="customFile" />
        <b-button @click="upload()">GoGoGO</b-button>
    </div>
</template>

<script>
    // import uploader from "../uploader";
    // require('dotenv').load();
    // var fs = require('fs');
    // var cloudinary = require('cloudinary').v2;  
    
    // cloudinary.uploader.upload("../2S7A0929.jpg", function(error, result) {console.log(result, error)});
    // cloudinary.v2.uploader.upload("dog.mp4", 
    //     {resource_type: "video", public_id: "myfolder/mysubfolder/my_dog",
    //     overwrite: true, notification_url: "https://mysite.example.com/notify_endpoint"},
    //     function(error, result) {console.log(result, error)});
    export default{
        name: "UploadMedia",
        mounted() {
            console.log("upload component created");
        },
        methods:{
            upload(){
                // this.$root.stote.runUploader("das");
                // const uploadImage  = require("../uploader");
                const imagePath = this.uploadFile("../2S7A0929.jpg");
                // this.uploadFile("../2S7A0929.jpg");
            },
            async uploadFile(filePath) {
                const {Storage} = require('@google-cloud/storage');
                const storage = new Storage();
                try{
                    await storage.bucket(noambk).upload(filePath, {
                    destination: destFileName,
                    });
                    console.log(`${filePath} uploaded to ${bucketName}`);
                }catch(error){
                    console.error;
                }

            }

        }
        // data(){
        //     return{
        //             uploads: {},
        //     }
        // },
        // methods: {
        //     fileUpload(){
        //         cloudinary.uploader.upload('../2S7A0929.jpg', { tags: 'basic_sample' }, function (err, image) {
        //             console.log();
        //             console.log("** File Upload");
        //             if (err) { console.warn(err); }
        //             console.log("* public_id for the uploaded image is generated by Cloudinary's service.");
        //             console.log("* " + image.public_id);
        //             console.log("* " + image.url);
        //             waitForAllUploads("pizza", err, image);
        //             });
        //     }
        // },
        // mounted() {
        //     cloudinary.config({ 
        //         cloud_name: 'league-managmant', 
        //         api_key: '935664579256949', 
        //         api_secret: 'PYWy7BQaiHW6ZZ_4o-GJt-XhU5U' 
        //         });
        // },
    };
</script>